### ISSUE TITLE
Upsert: add field renaming

### ISSUE THREAD

**Issue by jacobdadams** [agrc/palletjack#18]
~For example, an enterprise gdb in postgres stores length as `st_length(shape)` while AGOL stores it as `Shape__Length` (note double underscore).~

Edit: geometry was a red herring. Still, adding field mapper to allow field renaming if needed.

**Comment by steveoh** [comment]
These are auto generated and should not be updated explicitly. I'm not sure they will let you update them explicitly. I think they can safely be ignored completely and the feature service will manage them.

**Comment by jacobdadams** [comment]
hmm, I'll have to test. It makes sense that they're auto-generated, but previous file gdb to AGOL updates have worked the shape/area fields included... I wonder if it's just ignoring them. Time to test.

**Comment by steveoh** [comment]
What was the result of those tests?

**Comment by jacobdadams** [comment]
I've only ever really worked with palletjack on point data. There are a lot more considerations for polygon data, and I also need to add some sanity checks for projections. The field renaming may still be useful, so I pushed that through on its own.
