### ISSUE TITLE
DataCleaning.switch_to_float() can't handle commas in numbers

### ISSUE THREAD

**Issue by jacobdadams** [agrc/palletjack#50]
Throws `ValueError: could not convert string to float: '2,115.88': Error while type casting for column ...` 

Figure out a way to parse the string better- either strip out commas, or see if there's a built-in tool that handles them better (like csv's `thousands=` parameter)

**Comment by steveoh** [comment]
https://docs.python.org/3/library/locale.html?highlight=locale#locale.atof
